[profile.default]
solc = "0.8.21"
bytecode_hash = "none"
optimizer = true
via_ir = true
optimizer_runs = 1000000
no_match_path = "*/integration/*"
# needed for marktoda/forge-gas-snapshot
ffi = true
fs_permissions = [{ access = "read-write", path = ".forge-snapshots/"}]

[profile.integration]
no_match_path = ""
match_path = "*/integration/*"

[fuzz]
runs = 100_000
