[profile.default]
solc = "0.8.21"
bytecode_hash = "none"
optimizer = true
via_ir = true
optimizer_runs = 1000000
no_match_path = "*/integration/*"
fuzz_runs = 10000
# needed for marktoda/forge-gas-snapshot
ffi = true
fs_permissions = [{ access = "read-write", path = ".forge-snapshots/"}]
evm_version = "shanghai"

[profile.integration]
no_match_path = ""
match_path = "*/integration/*"
evm_version = "shanghai"
