name: gas

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  gas:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Check gas snapshots
        run: forge snapshot --check

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Install Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: Install node dependencies
        run: npm install
      - name: Install node dependencies
        run: npm run compare_gas:ci
